name: Pre-release workflow

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build:
    name: Create Release Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Pre-release
        id: create_pre-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Pre-release ${{ github.ref }}
          body: |
            Something has changed
          draft: false
          prerelease: true
